name: Custom Action

description: 'Run a script from the mayo repository'

runs:
  using: 'composite'
  steps:
    - name: Download Substrate Template
      uses: actions/checkout@v2
      with:
          repository: First-Repo
          ref: main
          path: substrate-node-template
