name: 'Delete Shell Script Action'
description: 'This action runs a shell script from another repository.'

inputs:
  script-repo:
    description: 'Repository where the script is located'
    required: true
    default: 'First-Repo'
  script-path:
    description: 'Path to the shell script within the repository'
    required: true
    default: 'test-01-repo/delete_shell.sh'

runs:
  using: 'composite'
  steps:
    - name: Checkout the action repository
      uses: actions/checkout@v3

    - name: Checkout the script repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.script-repo }}
        path: 'repo'

    - name: Run delete shell script
      run: |
        chmod +x ./repo/${{ inputs.script-path }}
        ./repo/${{ inputs.script-path }}
