name: 'Python AppDynamics Automation'
description: 'A composite action to automate AppDynamics tests using Python.'

inputs:
  HOSTURL:
    description: 'The host URL for AppDynamics.'
    required: true
  USERNAME:
    description: 'The username for AppDynamics.'
    required: true
  CLIENT_SECRET:
    description: 'The client secret for AppDynamics.'
    required: true
  ACCOUNT_ID:
    description: 'The account ID for AppDynamics.'
    required: true
  AUTH_URI:
    description: 'The authentication URI for AppDynamics.'
    required: true
  TEST_TOKEN:
    description: 'The test token for GitHub API.'
    required: true

env:
  ACTION_PATH: '.github/actions/'

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install argparse configparser requests urllib3
      shell: bash

    - name: Create credentials.ini
      run: |
        echo "[credentials]
        hosturl=${{ inputs.HOSTURL }}
        username=${{ inputs.USERNAME }}
        clientsecret=${{ inputs.CLIENT_SECRET }}
        accountid=${{ inputs.ACCOUNT_ID }}
        authuri=${{ inputs.AUTH_URI }}" > credentials.ini
        cat credentials.ini
      shell: bash

    - name: Run AppDynamics tests
      run: |
        #python .github/actions/service_endpoint/test1.py --creds credentials.ini
        #python .github/actions/service_endpoint/bt_csv.py
        chmod +x ./test.sh
        ./test.sh
      shell: bash

    - name: Upload generated bt.csv as artifact
      uses: actions/upload-artifact@v4
      with:
        name: bt-report
        path: bt.csv
      env:
        GITHUB_TOKEN: ${{ inputs.TEST_TOKEN }}
