name: 'Run Shell Script Action'
description: 'This action copies a shell script from another repository and runs it.'

inputs:
  script-repo:
    description: 'Repository where the script is located'
    required: true
    default: 'First-Repo'
  script-path:
    description: 'Path to the shell script within the repository'
    required: true
    default: 'test-01-repo/delete_shell.sh'

runs:
  using: 'composite'
  steps:
    - name: Checkout the action repository
      uses: actions/checkout@v3

    - name: Checkout the repository containing the script
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.script-repo }}
        path: 'repo'

    - name: Copy delete_shell.sh script to action folder
      run: |
        cp ./test-01-repo/delete_shell.sh .github/actions/delete_shell.sh
        chmod +x .github/actions/delete_shell.sh
        ls -l .github/actions/
      shell: bash  # Add the shell property here

    - name: Run delete_shell.sh script
      run: |
        .github/actions/delete_shell.sh
      shell: bash  # Add the shell property here
