name: Custom Action

description: 'Run a script from the mayo repository'

inputs:
  example-input:
    description: 'An example input'
    required: true
    default: 'Hello World'

runs:
  using: 'composite'
  steps:
    - name: Checkout the first repository
      uses: actions/checkout@v2
      with:
        repository: 'First-Repo'
        ref: 'main'

    - name: Checkout the second repository (mayo)
      uses: actions/checkout@v2
      with:
        repository: 'mayo'
        ref: 'main'
        path: '/tmp/mayo'

    - name: Copy test.sh from mayo repo
      run: |
        cp /tmp/mayo/test.sh First-Repo/.github/actions/test.sh
        chmod +x First-Repo/.github/actions/test.sh

    - name: Run test.sh script
      run: ./First-Repo/.github/actions/test.sh
