name: "Run Remote Shell Script"
description: "This action checks out two repositories and runs the shell script."

inputs:
  repo2_branch:
    description: 'Branch name of the second repository (main)'
    required: true
    default: 'main'

runs:
  using: 'composite'
  steps:
    # Checkout the first repository (First-Repo)
    - name: Checkout First-Repo
      uses: actions/checkout@v3

    # Checkout the second repository (First-Repo/test-01-repo)
    - name: Checkout test-01-repo
      uses: actions/checkout@v3
      with:
        repository: 'First-Repo/test-01-repo'
        ref: '${{ inputs.repo2_branch }}'  # Checkout the main branch

    # Run the shell script from the second repository
    - name: Run delete_shell.sh from test-01-repo
      run: |
        chmod +x ./test-01-repo/delete_shell.sh
        ./test-01-repo/delete_shell.sh  # Run the script
      shell: bash  # Add the shell type here
