name: 'Docker Compose Action'
description: 'This action builds and uploads a Docker image using Docker Compose.'

inputs:
  version:
    description: 'Docker Compose version to install'
    required: false
    default: '1.29.2'

runs:
  using: 'docker'
  image: 'docker:latest'
  steps:
    - name: Set up Docker Compose
      run: |
        curl -L "https://github.com/docker/compose/releases/download/${{ inputs.version }}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Build and push Docker image using docker-compose
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
