name: AppDynamics

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  automated_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run the AppDynamics automation action
        uses: ./.github/actions 
        with:
          HOSTURL: 'https://mayotest.saas.appdynamics.com'
          USERNAME: 'WA30289@mayotest'
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }} 
          ACCOUNT_ID: 'mayotest' 
          AUTH_URI: '/api/oauth/accesss_token'
          cred_file: '.github/actions/credentials.ini' 
          debug_level: '5' 
          output_format: 'json' 
          app_name: 'Patient_Online_Services_Portal_Test' 
          transaction_name: 'all_business_transactions_list' 
