name: Secure Credentials Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up credentials.ini from the template with secrets (excluding HOSTURL)
      - name: Set up credentials.ini
        run: |
          sed "s|REPLACE_WITH_HOSTURL|${{ env.HOSTURL }}|" credentials-template.ini | \
          sed "s|REPLACE_WITH_USERNAME|${{ secrets.USERNAME }}|" | \
          sed "s|REPLACE_WITH_CLIENT_SECRET|${{ secrets.CLIENT_SECRET }}|" | \
          sed "s|REPLACE_WITH_ACCOUNT_ID|${{ secrets.ACCOUNT_ID }}|" | \
          sed "s|REPLACE_WITH_AUTHURI|${{ secrets.AUTHURI }}|" > credentials.ini

      - name: Run script using credentials
        run: |
          python test.py --creds credentials.ini
          
        env:
          CREDENTIALS_PATH: test-01-repo/credentials.ini 
