name: Secure Credentials Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up credentials.ini from the template with secrets (excluding HOSTURL)
      - name: Set up credentials.ini from template
        run: |
          # Replace placeholders with actual values from secrets and env variables
          sed "s|REPLACE_WITH_HOSTURL|${{ env.HOSTURL }}|" credentials-template.ini | \
          sed "s|REPLACE_WITH_USERNAME|${{ secrets.USERNAME }}|" | \
          sed "s|REPLACE_WITH_CLIENT_SECRET|${{ secrets.CLIENT_SECRET }}|" | \
          sed "s|REPLACE_WITH_ACCOUNT_ID|${{ secrets.ACCOUNT_ID }}|" | \
          sed "s|REPLACE_WITH_AUTHURI|${{ secrets.AUTHURI }}|" > credentials.ini

      - name: Print generated credentials.ini (for debugging)
        run: |
          cat credentials.ini  # Only for debugging, do not expose secrets in production

      # Run Python script with the generated credentials.ini
      - name: Run script using credentials
        run: |
          python ./test-01-repo/test.py --creds credentials.ini
        # If you need to set the environment variable for your script
        env:
          CREDENTIALS_PATH: ./credentials.ini
          # Include other environment variables if needed
