name: Secure Credentials Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up credentials.ini from the template with secrets (excluding HOSTURL)
      - name: Set up credentials.ini
        run: |
          sed "s|HOSTURL|${{ env.HOSTURL }}|" | \
          sed "s|USERNAME|${{ secrets.USERNAME }}|" | \
          sed "s|CLIENT_SECRET|${{ secrets.CLIENT_SECRET }}|" | \
          sed "s|ACCOUNT_ID|${{ secrets.ACCOUNT_ID }}|" | \
          sed "s|AUTHURI|${{ secrets.AUTHURI }}|" > credentials.ini

      - name: Run script using credentials
        run: |
          python ./test-01-repo/test.py --creds credentials.ini --uri "/controller/rest/applications/22386/business-transactions?output=JSON" --output bt.json
          
        env:
          CREDENTIALS_PATH: ./test-01-repo/credentials.ini 
