name: Run Python Test

on:
  push:
    branches:
      - main  # Run this workflow when pushing to the main branch (or another branch)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install -r requirements.txt  # Make sure to include dependencies like `requests` in your requirements.txt file

      - name: Create credentials.ini file with secrets
        run: |
          echo "[credentials]" > ./test-01-repo/credentials.ini
          sed "s|HOSTURL|${{ env.HOSTURL }}|" ./template_credentials.ini | \
          sed "s|USERNAME|${{ secrets.USERNAME }}|" | \
          sed "s|CLIENT_SECRET|${{ secrets.CLIENT_SECRET }}|" | \
          sed "s|ACCOUNT_ID|${{ secrets.ACCOUNT_ID }}|" | \
          sed "s|AUTH_URI|${{ secrets.AUTHURI }}|" >> ./test-01-repo/credentials.ini
        env:
          HOSTURL: ${{ secrets.HOSTURL }}  # Set the environment variable for HOSTURL
          
      - name: Run the Python test script
        run: |
          python ./test-01-repo/test.py --creds ./test-01-repo/credentials.ini
