name: Example Workflow with Credentials

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up credentials.ini from the template (no secrets exposed in logs)
      - name: Set up credentials.ini
        run: |
          sed "s|USERNAME|${{ secrets.CREDENTIALS_USERNAME }}|" credentials-template.ini | \
          sed "s|PASSWORD|${{ secrets.CREDENTIALS_PASSWORD }}|" | \
          sed "s|API_KEY|${{ secrets.CREDENTIALS_API_KEY }}|" > credentials.ini

      # Use the credentials in a safe manner
      - name: Run script using credentials
        run: |
          # Using credentials securely (e.g., passing to a script or command)
          python my_script.py --config credentials.ini
        env:
          CREDENTIALS_PATH: test-01-repo/credentials.ini  # Passing the path to the script, not printing secrets

