name: Secure Credentials Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up credentials.ini from the template with secrets and env variables
      - name: Set up credentials.ini from template
        run: |
          # Replace placeholders in credentials-template.ini with actual values
          sed "s|HOSTURL|${{ env.HOSTURL }}|" credentials-template.ini | \
          sed "s|USERNAME|${{ secrets.USERNAME }}|" | \
          sed "s|CLIENT_SECRET|${{ secrets.CLIENT_SECRET }}|" | \
          sed "s|ACCOUNT_ID|${{ secrets.ACCOUNT_ID }}|" | \
          sed "s|AUTH_URI|${{ secrets.AUTHURI }}|" > credentials.ini

      # Debugging: print the generated credentials.ini file (only for debugging)
      - name: Print credentials.ini for debugging
        run: |
          cat credentials.ini
