name: Secure Credentials Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Verify if credentials-template.ini exists in the repo
      - name: Verify credentials-template.ini exists
        run: |
          ls -l credentials-template.ini

      # Set up credentials.ini from the template with secrets and env variables
      - name: Set up credentials.ini from template
        run: |
          # Replace placeholders in credentials-template.ini with actual values
          sed "s|HOSTURL|${{ env.HOSTURL }}|" credentials-template.ini | \
          sed "s|USERNAME|${{ secrets.USERNAME }}|" | \
          sed "s|CLIENT_SECRET|${{ secrets.CLIENT_SECRET }}|" | \
          sed "s|ACCOUNT_ID|${{ secrets.ACCOUNT_ID }}|" | \
          sed "s|AUTH_URI|${{ secrets.AUTHURI }}|" > credentials.ini

      # Print the generated credentials.ini for debugging (remove in production)
      - name: Print credentials.ini for debugging
        run: |
          cat credentials.ini

      # Run Python script using the generated credentials
      - name: Run script using credentials
        run: |
          python ./test-01-repo/test.py --creds credentials.ini
