name: Run Python AppDynamics

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/credentials.yml
      - .github/actions/*
      - credentials.ini

permissions: write-all

jobs:
  automated_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
  
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install argparse configparser requests urllib3

      - name: Create credentials.ini with replaced values
        run: |
          cat <<EOF > credentials.ini
          [credentials]
          hosturl=${{ vars.HOSTURL }}
          username=${{ secrets.USERNAME }}
          clientsecret=${{ secrets.CLIENT_SECRET }}
          accountid=${{ secrets.ACCOUNT_ID }}
          authuri=${{ secrets.AUTH_URI }}
          EOF
          
          # Print the credentials.ini to verify
          cat credentials.ini

      - name: Run the AppDynamics test scripts
        run: |
          python .github/actions/test.py --creds credentials.ini
          python .github/actions/test.py --creds credentials.ini
          
      - name: Upload generated bt.json as artifact
        uses: actions/upload-artifact@v3
        with:
          name: bt-report
          path: bt.json
