name: Run Python Script Every Minute

on:
  push:
    branches:
      - main  # or your default branch
  schedule:
    - cron: '*/1 * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository to access your Python script

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # You can specify the Python version you want

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip if needed
          pip install -r requirements.txt || true  # Install dependencies, if you have a requirements.txt file

      - name: Run Python script
        run: python hello_world.py  # Run the Python script
