name: Run Hello World Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'   # Run every minute

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
        
      - name: Run Python script
        run: python hello_world.py
