name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Dockerfile from external repository
      run: |
        curl -LJO https://github.com/Ajithkumar8006/First-Repo/blob/main/Dockerfile
        curl -LJO https://github.com/Ajithkumar8006/First-Repo/blob/main/app.py
        curl -LJO https://github.com/Ajithkumar8006/First-Repo/blob/main/requirements.txt
      working-directory: .github/actions

    - name: Build Docker image
      run: |
        docker build -t my-docker-image .
     
    - name: Run Docker container
      run: |
        docker run -d --name my-container my-docker-image
