name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Download Dockerfile from external repository
      run: |
        mkdir -p /tmp/
        curl -L -o /tmp/Dockerfile https://raw.githubusercontent.com/Ajithkumar8006/First-Repo/main/Dockerfile
        curl -L -o /tmp/app.py https://raw.githubusercontent.com/Ajithkumar8006/First-Repo/main/app.py
        curl -L -o /tmp/requirements.txt https://raw.githubusercontent.com/Ajithkumar8006/First-Repo/main/requirements.txt

    - name: Build Docker image
      run: |
        cd /tmp/
        docker build -t my-docker-image .

    - name: Run Docker container
      run: |
        docker run -d --name my-container my-docker-image
