name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Docker
      run: |
        # Remove conflicting Docker versions to avoid conflicts
        sudo apt-get remove -y docker docker-engine docker.io containerd runc
        
        # Update apt package index
        sudo apt-get update
        
        # Install required packages for Docker installation
        sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          software-properties-common
        
        # Add Docker’s official GPG key
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        
        # Set up Docker repository
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        
        # Install Docker CE (Community Edition)
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        
        # Check if Docker is installed successfully
        docker --version

    - name: Ensure correct permissions for /tmp/
      run: |
        # Limiting permissions to just the working directory for safety
        sudo chmod -R 777 /tmp/

    - name: Download Dockerfile from external repository
      run: |
        mkdir -p /tmp/
        curl -L -o /tmp/Dockerfile https://raw.githubusercontent.com/Ajithkumar8006/First-Repo/main/Dockerfile
        curl -L -o /tmp/app.py https://raw.githubusercontent.com/Ajithkumar8006/First-Repo/main/app.py
        curl -L -o /tmp/requirements.txt https://raw.githubusercontent.com/Ajithkumar8006/First-Repo/main/requirements.txt

    - name: Build Docker image
      run: |
        cd /tmp/
        docker build -t my-docker-image .

    - name: Run Docker container
      run: |
        docker run -d --name my-container my-docker-image
    - name: Save Docker image as tarball
      run: |
        # Save the built Docker image as a tarball (.tar)
        docker save my-docker-image > /tmp/my-docker-image.tar

    - name: Upload Docker image as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: my-docker-image
        path: /tmp/my-docker-image.tar
