name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Docker
      run: |
        sudo apt-get remove -y docker docker-engine docker.io containerd runc
        sudo apt-get update
        sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Ensure correct permissions for /tmp/
      run: |
        sudo chmod -R 777 /tmp/

    - name: Download Dockerfile from external repository
      run: |
        mkdir -p /tmp/
        curl -L -o /tmp/Dockerfile https://raw.githubusercontent.com/Ajithkumar8006/First-Repo/main/Dockerfile
        curl -L -o /tmp/app.py https://raw.githubusercontent.com/Ajithkumar8006/First-Repo/main/app.py
        curl -L -o /tmp/requirements.txt https://raw.githubusercontent.com/Ajithkumar8006/First-Repo/main/requirements.txt

    - name: Build Docker image
      run: |
        cd /tmp/
        docker build -t my-docker-image .

    - name: Run Docker container
      run: |
        docker run -d --name my-container my-docker-image
