name: Cron Job Every Minute

on:
workflow_dispatch

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Echo Hello World
      run: echo "Hello World"
