name: Run Shell Script from Remote Repository
on:
  push:
    branches:
      - 'main'  # Trigger on push to the main branch of the First-Repo
  pull_request:
    branches:
      - 'main'  # Trigger on PR targeting the main branch
permissions:
  contents: write
  actions: write

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repository (First-Repo)
      - name: Checkout First-Repo
        uses: actions/checkout@v3

      # Step 2: Checkout the second repository (mayo)
      - name: Checkout mayo repo
        uses: actions/checkout@v3
        with:
          repository: 'mayo'
          ref: 'main'  # Branch in the second repository (mayo)
          token: ${{ secrets.GITHUB_TOKEN }}  # Use token for private repositories

      # Step 3: Run the custom action defined in First-Repo/.github/actions/action.yaml
      - name: Run Action to Trigger Shell Script
        uses: ./.github/actions  # Default action path in the same repo (First-Repo)
        with:
          repo2_branch: 'main'  # Branch in the second repository (mayo) to check out
