name: Run Test Script

on:
  push:
    branches:
      - main

jobs:
  run-test-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout First-Repo repository
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Checkout mayo repository
        uses: actions/checkout@v2
        with:
          repository: 'mayo/test.sh'
          ref: 'main'
          path: '/tmp/mayo'

      - name: Run action to clone and run test.sh from mayo repository
        uses: ./github/actions  # Reference to the local action in First-Repo/.github/actions
        with:
          example-input: 'Some input if needed'
