name: Run Test Script

on:
  pull:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  run-test-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout First-Repo repository
        uses: actions/checkout@v2
        with:
          ref: 'main'
          
      - name: Run the AppDynamics automation action
        uses: ./.github/actions 
