name: Run Shell Script from Remote Repository
on:
  push:
    branches:
      - 'main'  # Trigger on push to the main branch
  pull_request:
    branches:
      - 'main'  # Trigger on PR targeting the main branch

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository (First-Repo)
    - name: Checkout First-Repo
      uses: actions/checkout@v3

      # Use the action defined in First-Repo/.github/actions/action.yaml
    - name: Run Action to Trigger Shell Script
      uses: ./.github/actions  # Default action path (relative to the repo)
      with:
        repo2_branch: 'main'  # Branch in the second repository (test-01-repo) to check out
