name: Run Shell Script from Remote Repository
on:
  push:
    branches:
      - 'main'  # Trigger on push to the main branch of the First-Repo
  pull_request:
    branches:
      - 'main'  # Trigger on PR targeting the main branch

permissions:
  contents: read  # Grants GITHUB_TOKEN permission to read contents of the repository
  actions: read   # Grants read access to actions (actions/checkout, etc.)

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current repository (First-Repo)
      - name: Checkout First-Repo
        uses: actions/checkout@v3

      # Step 2: Checkout the second repository (mayo)
      - name: Checkout mayo repo
        uses: actions/checkout@v3
        with:
          repository: 'Ajithkumar8006/mayo'  # Full repository path (replace with the actual owner/repo)
          ref: 'main'  # Branch name in the mayo repo
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the automatically provided token for authentication
          ssh-strict: true
          persist-credentials: true
          clean: true
          sparse-checkout-cone-mode: true
          fetch-depth: 1
          fetch-tags: false
          lfs: false
          submodules: false
          set-safe-directory: true

      # Step 3: Run the custom action defined in First-Repo/.github/actions/action.yaml
      - name: Run Action to Trigger Shell Script
        uses: ./.github/actions/action  # Use the action from the current repository
        with:
          repo2_branch: 'main'  # Branch in the second repository (mayo)
