name: Run Delete Shell Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Shell Script Action
      uses: ./First-Repo/.github/actions  # Path to the custom action
      with:
        script-repo: 'First-Repo'         # Repository containing the script
        script-path: 'test-01-repo/delete_shell.sh'
