name: Authenticate AppDynamics and Run Script

on:
  push:
    branches:
      - main

jobs:
  appdynamics-auth-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python (needed to run your Python script)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Create credentials.ini file with the replaced values
      - name: Create credentials.ini with replaced values
        run: |
          # Replace placeholders in the credentials.ini file using sed
          echo "[credentials]" > credentials.ini
          sed "s|HOSTURL|${{ secrets.HOSTURL }}|" > credentials.ini
          sed -i "s|USERNAME|${{ secrets.USERNAME }}|" credentials.ini
          sed -i "s|CLIENT_SECRET|${{ secrets.CLIENT_SECRET }}|" credentials.ini
          sed -i "s|ACCOUNT_ID|${{ secrets.ACCOUNT_ID}}|" credentials.ini
          sed -i "s|AUTHURI|${{ secrets.AUTHURI }}|" credentials.ini

      # Run the Python script with the credentials.ini file
      - name: Run the AppDynamics test script
        run: |
          python ./test-01-repo/test.py --creds credentials.ini
